### ISSUE TITLE
IOS 12 support please

### ISSUE THREAD

**Issue by SergeKZ** [KJCracks/Clutch#228] opened 2019-02-25 08:52 UTC
please add support ios 12

**Comment by Tatsh** [comment] 2019-02-25 09:16
What doesn't work on iOS 12?

I do not have a device here to test with. I don't suspect there are any issues building this project for iOS 12.

Also, we cannot do anything if the jailbreak you are using has invalid kernel patches for this purpose.

**Comment by talfstad** [comment] 2019-02-26 03:53
in 12.1.1 here's my error:

<img width="852" alt="clutch error" src="https://user-images.githubusercontent.com/2826082/53386379-da992e80-3936-11e9-8534-bc515ba95130.png">

**Comment by Tatsh** [comment] 2019-02-26 04:11
That is a strange error as I do not see why a jailbroken iOS would ever care about code signing. Jailbreaks are supposed to patch [AMFI](https://www.theiphonewiki.com/wiki/AppleMobileFileIntegrity). [Maybe you have to inject Clutch into the cache?](https://github.com/pwn20wndstuff/Undecimus/issues/498#issuecomment-466818532)

*CT policy* refers to certificate transparency policy.

**Comment by JoniVR** [comment] 2019-02-27 13:26
You mean injecting it into the trust cache like this?
![image](https://user-images.githubusercontent.com/7591717/53493332-6926c080-3a9b-11e9-9201-b434e345b6fa.png)

If that's what you meant, I tried it and I'm getting the same thing too. 
![image](https://user-images.githubusercontent.com/7591717/53493249-34b30480-3a9b-11e9-8dca-6e9d61f2f0da.png)

Clutch itself just says:
```Killed: 9```

Is there anything I'm missing?

**Comment by JoniVR** [comment] 2019-02-27 17:52
@Tatsh 	
This worked for me. 

easy copy pasta: 

```sh
# safe place to work in
cd /private/var/mobile/Documents
```


```sh
# Get the ent from bash and save it
ldid -e `which bash` > ent.xml
```

```sh
# sign Clutch with the ent.
ldid -S ent.xml `which Clutch`
```

```sh
# inject into trust cache
inject `which Clutch`
```

**Comment by Tatsh** [comment] 2019-02-28 09:17
What is the output of

```sh
ldid -e `which bash`
```

?

**Comment by JoniVR** [comment] 2019-02-28 09:21
```html
<?xml version="1.0" encoding="UTF-8"?>             
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> 
<plist version="1.0">                              
<dict>                                             
        <key>platform-application</key>            
        <true/>                                    
        <key>com.apple.private.skip-library-validation</key>                                           
        <true/>                                    
        <key>com.apple.private.security.no-container</key>                                             
        <true/>                                    
</dict>                                            
</plist>
```

**Comment by Tatsh** [comment] 2019-02-28 09:36
Maybe we can sign with those during the build process on macOS but I am not sure. Usually if you sign with `com.apple.private.` stuff on macOS the binary is never allowed to run because only Apple can sign with those entitlements, but since you have to run `inject` it probably works around that.

**Comment by JoniVR** [comment] 2019-02-28 12:12
Could give it a shot yes, either that or add the steps on how to do it manually on device to the documentation perhaps?

**Comment by insomnia417** [comment] 2019-02-28 17:47
ios12.1.1b3 can't work too.

**Comment by GL8666** [comment] 2019-03-01 01:46
> @Tatsh
> This worked for me.
> 
> easy copy pasta:
> 
> ```shell
> # safe place to work in
> cd /private/var/mobile/Documents
> ```
> 
> ```shell
> # Get the ent from bash and save it
> ldid -e `which bash` > ent.xml
> ```
> 
> ```shell
> # sign Clutch with the ent. "-Sent.xml" is the correct usage
> ldid -Sent.xml `which Clutch`
> ```
> 
> ```shell
> # inject into trust cache
> inject `which Clutch`
> ```

It's work for me too

**Comment by Tatsh** [comment] 2019-03-01 01:53
The changes are in. If this is good @SergeKZ , please close the bug (or I will close it after a time).

**Closed** 2019-03-01 03:13 UTC

**Comment by esterTion** [comment] 2019-03-03 05:51
Sorry, but I still can't get clutch to properly work on iOS 12
I signed with entitlements from repo and my own cert obtained by xcode to prevent CT error. For some reason my device would panic later if I ever use `inject`
I also tried ldid signed bin & inject, and bin built from latest source, they all run into same problem. 

Clutch is important to me as this game (PuriCone) will exit immediately in jailbroken env (detection by [CrackProof](https://www.hypertech.co.jp/en/products/crackproof-for-ios/)), thus other kind of "open the app then decrypt" methods won't work at all. 

```
root# Clutch-2.0.4 -b jp.co.cygames.princessconnectredive
Error: Could not obtain mach port, either the process is dead (codesign error?) or entitlements were not properly signed!

Error: Failed to dump <DefaultNotificationContent> with arch arm64

2019-03-03 13:37:38.123 Clutch-2.0.4[1017:13598] failed operation :(
2019-03-03 13:37:38.123 Clutch-2.0.4[1017:13598] application <NSOperationQueue: 0x101fc3e10>{name = 'NSOperationQueue 0x101fc3e10'}
Error: Failed to dump <DefaultNotificationContent>

2019-03-03 13:37:38.123 Clutch-2.0.4[1017:13598] failed operation :(
2019-03-03 13:37:38.123 Clutch-2.0.4[1017:13598] application <NSOperationQueue: 0x101fc3e10>{name = 'NSOperationQueue 0x101fc3e10'}
Error: Could not obtain mach port, either the process is dead (codesign error?) or entitlements were not properly signed!

Error: Failed to dump <princessconnectredive> with arch arm64

2019-03-03 13:37:38.392 Clutch-2.0.4[1017:13599] failed operation :(
2019-03-03 13:37:38.392 Clutch-2.0.4[1017:13599] application <NSOperationQueue: 0x101fc0180>{name = 'NSOperationQueue 0x101fc0180'}
Error: Failed to dump <princessconnectredive>

2019-03-03 13:37:38.393 Clutch-2.0.4[1017:13599] failed operation :(
2019-03-03 13:37:38.393 Clutch-2.0.4[1017:13599] application <NSOperationQueue: 0x101fc0180>{name = 'NSOperationQueue 0x101fc0180'}
Error: Failed to dump jp.co.cygames.princessconnectredive :(

```

**Comment by Tatsh** [comment] 2019-03-03 10:30
Clutch does not try to defeat things like CrackProof. You will need other tools.

**Comment by esterTion** [comment] 2019-03-03 10:35
> Clutch does not try to defeat things like CrackProof. You will need other tools.

Clutch worked on iOS 9, and this is just an example dump. 
It fails on every app on iOS 12. 

Clutch include executables as library prevented them from executing any detection. (I think this is how Clutch works?)

**Comment by Tatsh** [comment] 2019-03-03 10:51
iOS 12 has changed a lot of things and I do not own a device to test with so I cannot verify what users are saying whether things or work or not. From what I can tell, the unc0ver jailbreak is as unstable as any post iOS 9 jailbreaks and is still beta.

**Comment by victor1342** [comment] 2019-03-08 13:35
Can this be reopened please? Clutch can't dump IPAs on iOS 12 and there's no sign that the issue is related to bugs in unc0ver.

**Comment by paradiseduo** [comment] 2019-05-06 08:58
> @Tatsh
> This worked for me.
> 
> easy copy pasta:
> 
> ```shell
> # safe place to work in
> cd /private/var/mobile/Documents
> ```
> 
> ```shell
> # Get the ent from bash and save it
> ldid -e `which bash` > ent.xml
> ```
> 
> ```shell
> # sign Clutch with the ent. "-Sent.xml" is the correct usage
> ldid -Sent.xml `which Clutch`
> ```
> 
> ```shell
> # inject into trust cache
> inject `which Clutch`
> ```

This worked for me!

**Comment by tataevr** [comment] 2019-07-31 16:38
> in 12.1.1 here's my error:
> 
> <img alt="clutch error" width="852" src="https://user-images.githubusercontent.com/2826082/53386379-da992e80-3936-11e9-8534-bc515ba95130.png">
> 
> This causes an immediate exit with a stdout message `Killed: 9`

Can you please tell me, where did you get this error log? I mean what you used to get it?

**Comment by esterTion** [comment] 2019-07-31 16:42
> 
> Can you please tell me, where did you get this error log? I mean what you used to get it?

There is `Apple Configurator 2` app on macOS, and `idevicesyslog` in `libimobiledevice`

**Comment by tataevr** [comment] 2019-07-31 16:45
@esterTion got it. Will check that out right now. Thank you!

**Comment by SummerHF** [comment] 2020-05-04 02:06
> @Tatsh
> This worked for me.
> 
> easy copy pasta:
> 
> ```shell
> # safe place to work in
> cd /private/var/mobile/Documents
> ```
> 
> ```shell
> # Get the ent from bash and save it
> ldid -e `which bash` > ent.xml
> ```
> 
> ```shell
> # sign Clutch with the ent. "-Sent.xml" is the correct usage
> ldid -Sent.xml `which Clutch`
> ```
> 
> ```shell
> # inject into trust cache
> inject `which Clutch`
> ```

-sh: inject: command not found

> @Tatsh
> This worked for me.
> 
> easy copy pasta:
> 
> ```shell
> # safe place to work in
> cd /private/var/mobile/Documents
> ```
> 
> ```shell
> # Get the ent from bash and save it
> ldid -e `which bash` > ent.xml
> ```
> 
> ```shell
> # sign Clutch with the ent. "-Sent.xml" is the correct usage
> ldid -Sent.xml `which Clutch`
> ```
> 
> ```shell
> # inject into trust cache
> inject `which Clutch`
> ```

get error `-sh: inject: command not found`, what should i do please?

**Comment by SummerHF** [comment] 2020-05-04 02:12
> @Tatsh
> This worked for me.
> 
> easy copy pasta:
> 
> ```shell
> # safe place to work in
> cd /private/var/mobile/Documents
> ```
> 
> ```shell
> # Get the ent from bash and save it
> ldid -e `which bash` > ent.xml
> ```
> 
> ```shell
> # sign Clutch with the ent. "-Sent.xml" is the correct usage
> ldid -Sent.xml `which Clutch`
> ```
> 
> ```shell
> # inject into trust cache
> inject `which Clutch`
> ```

get error `-sh: inject: command not found` what should i do, please?

**Comment by paradiseduo** [comment] 2020-05-04 05:22
> > @Tatsh
> > This worked for me.
> > easy copy pasta:
> > ```shell
> > # safe place to work in
> > cd /private/var/mobile/Documents
> > ```
> > 
> > 
> > ```shell
> > # Get the ent from bash and save it
> > ldid -e `which bash` > ent.xml
> > ```
> > 
> > 
> > ```shell
> > # sign Clutch with the ent. "-Sent.xml" is the correct usage
> > ldid -Sent.xml `which Clutch`
> > ```
> > 
> > 
> > ```shell
> > # inject into trust cache
> > inject `which Clutch`
> > ```
> 
> get error `-sh: inject: command not found` what should i do, please?

inject只支持使用unc0ver的越狱方式越狱的手机

**Comment by SummerHF** [comment] 2020-05-04 05:34
> > > @Tatsh 
嗯嗯嗯, 用的checkra1n自然是敲不出来这个了 谢谢

**Comment by armnotstrong** [comment] 2020-11-09 12:08
> @Tatsh
> This worked for me.
> 
> easy copy pasta:
> 
> ```shell
> # safe place to work in
> cd /private/var/mobile/Documents
> ```
> 
> ```shell
> # Get the ent from bash and save it
> ldid -e `which bash` > ent.xml
> ```
> 
> ```shell
> # sign Clutch with the ent. "-Sent.xml" is the correct usage
> ldid -Sent.xml `which Clutch`
> ```
> 
> ```shell
> # inject into trust cache
> inject `which Clutch`
> ```

new to `unc0ver` did the tool `inject` shipped with the `unc0ver` jailbreak tool kit or should I install that command myself.

Didn't find the command `inject` with iPhone 6s/ iOS 12.1.4  jailbreaked with `unc0ver`

**Comment by liaoshl** [comment] 2021-06-22 07:44
> > @Tatsh
> > This worked for me.
> > easy copy pasta:
> > ```shell
> > # safe place to work in
> > cd /private/var/mobile/Documents
> > ```
> > 
> > 
> > ```shell
> > # Get the ent from bash and save it
> > ldid -e `which bash` > ent.xml
> > ```
> > 
> > 
> > ```shell
> > # sign Clutch with the ent. "-Sent.xml" is the correct usage
> > ldid -Sent.xml `which Clutch`
> > ```
> > 
> > 
> > ```shell
> > # inject into trust cache
> > inject `which Clutch`
> > ```
> 
> New to `unc0ver` did the tool `inject` shipped with the `unc0ver` jailbreak tool kit or should I install that command myself?
> 
> Didn't find the command `inject` with iPhone 6s/ iOS 12.1.4 jailbreaked with `unc0ver`

mee to, have you found a solution?

**Comment by nb5p** [comment] 2022-01-22 05:56
> > > @Tatsh
> > > This worked for me.
> > > easy copy pasta:
> > > ```shell
> > > # safe place to work in
> > > cd /private/var/mobile/Documents
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```shell
> > > # Get the ent from bash and save it
> > > ldid -e `which bash` > ent.xml
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```shell
> > > # sign Clutch with the ent. "-Sent.xml" is the correct usage
> > > ldid -Sent.xml `which Clutch`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```shell
> > > # inject into trust cache
> > > inject `which Clutch`
> > > ```
> > 
> > 
> > New to `unc0ver` did the tool `inject` shipped with the `unc0ver` jailbreak tool kit or should I install that command myself?
> > Didn't find the command `inject` with iPhone 6s/ iOS 12.1.4 jailbreaked with `unc0ver`
> 
> mee to, have you found a solution?

Please install `science.xnu.injector`.

**Comment by Whyjsee** [comment] 2022-09-04 03:43
> > > > @Tatsh
> > > > 嗯嗯嗯, 用的checkra1n自然是敲不出来这个了 谢谢

想问下checkra1n的话要敲哪个命令呢
