### ISSUE TITLE
Failed to dump  WeChatWatchNativeExtension

### ISSUE THREAD

**Issue by xbinglzh** [KJCracks/Clutch#197] opened 2017-12-21 10:13 UTC
Zipping WeChat.app
Error: Failed to dump  WeChatWatchNativeExtension

2017-12-22 18:13:15.026 clutch[1169:2a03] failed operation :(
2017-12-22 18:13:15.029 clutch[1169:2a03] application <NSOperationQueue: 0x14d32890>{name = 'NSOperationQueue 0x14d32890'}
Killed: 9

**Comment by Tatsh** [comment] 2017-12-21 23:48
We have no way to dump Watch extensions no matter the format. We even tried and we cannot easily run arm32k binaries on iOS. If a Watch jailbreak comes along it will be possible.

Duplicate of #166

**Closed by Tatsh** 2017-12-21 23:48 UTC
