### ISSUE TITLE
Phone crashing when dumping framework

### ISSUE THREAD

**Issue by andermoran** [KJCracks/Clutch#213] opened 2018-04-10 02:44 UTC
# General information

* iOS version: 10.1
* Commit hash: 164baab51835bdaeb380fbbd3b5e94e8b4046c65
* App bundle ID: `com.toyopagroup.picaboo`
* App name: *Snapchat*
* Command used: example: `clutch -b 4`

# Note
Would like to mention that it crashed my iPhone on 2 separate apps using the mapbox framework. It it possible to not dump the frameworks?

# Log

`Anders-iPhone-6S:~ root# Clutch -b 4

2018-04-09 21:36:01.329 Clutch[240:4201] command: Only dump binary files from specified bundleID

Zipping Snapchat.app

Swapping architectures..

Swapping architectures..

Swapping architectures..

Dumping <SnapchatShareExt> (armv7)

Patched cryptid (32bit segment)

Dumping <SnapchatNotesContentExt> (armv7)

Patched cryptid (32bit segment)

Dumping <SnapchatTodayWidget> (armv7)

Patched cryptid (32bit segment)

Writing new checksum

Dumping <SnapchatNotesContentExt> (arm64)

Patched cryptid (64bit segment)

Writing new checksum

Writing new checksum

Dumping <SnapchatTodayWidget> (arm64)

Patched cryptid (64bit segment)

Writing new checksum

Writing new checksum

Swapping architectures..

Dumping <SnapchatShareExt> (arm64)

Patched cryptid (64bit segment)

Writing new checksum

Dumping <Snapchat> (armv7)

Patched cryptid (32bit segment)

Zipping SnapchatNotesContentExt.appex

Zipping SnapchatShareExt.appex

Zipping SnapchatTodayWidget.appex

Writing new checksum

Dumping <Snapchat> (arm64)

Patched cryptid (64bit segment)

Connection to localhost closed by remote host.

Connection to localhost closed.`

**Comment by Tatsh** [comment] 2018-04-12 23:46
Duplicate of #209

**Comment by Tatsh** [comment] 2018-04-12 23:46
Duplicate of #209

**Closed** 2018-04-12 23:46 UTC
