### ISSUE TITLE
Cannot Dump WatchOS 2 apps

### ISSUE THREAD

**Issue by AppleTechy** [KJCracks/Clutch#194] opened 2017-09-14 03:50 UTC
# General information

* iOS version: e.g 10.2,
* App bundle ID: `fm.overcast.overcast`
* App name: `Overcast`
* Command used: example: `clutch -d fm.overcast.overcast`

# Log
`fm.overcast.overcast contains watchOS 2 compatible application. It's not possible to dump watchOS 2 apps with Cluth 2.0.4 at this moment
Segmentation fault:11` I had already ran `ulimit -n 512` to fix this but it didn't seem to do anything. I don't mind if I can't dump the app I just want to be able to dump the ios app.

**Comment by Tatsh** [comment] 2017-09-14 20:16
Not likely until a public jailbreak exists for watchOS.

**Comment by xbinglzh** [comment] 2017-12-21 10:11
Error: Failed to dump <WeChatWatchNativeExtension>

**Comment by xbinglzh** [comment] 2017-12-21 10:11
Error: Failed to dump <WeChatWatchNativeExtension>   dump Failed

**Comment by xbinglzh** [comment] 2017-12-21 10:12
Error: Failed to dump  WeChatWatchNativeExtension  Dump Failed

**Comment by Tatsh** [comment] 2017-12-21 23:48
Duplicate of #166

**Closed by Tatsh** 2017-12-21 23:48 UTC
