### ISSUE TITLE
Failed to dump <ThreemaNotificationExtension>

### ISSUE THREAD

**Issue by stormlion227** [KJCracks/Clutch#188] opened 2017-06-16 04:24 UTC
![2017-06-16_06h31_42](https://user-images.githubusercontent.com/24723104/27212020-8140a30c-525d-11e7-9828-b2f940497837.png)

**Comment by Tatsh** [comment] 2017-12-21 23:52
Duplicate of #127

**Closed** 2017-12-21 23:52 UTC
