### ISSUE TITLE
Cannot dump InstagramNotificationExtension

### ISSUE THREAD

**Issue by haniag** [KJCracks/Clutch#177] opened 2017-04-16 07:17 UTC
I compiled latest commit (4b7d0d5), and then ran: `ldid -SClutch.entitlements clutch`. However, still getting error, where only the extension is being dumped. To be clear, I ran ldid on device, and then rebooted it to clear cache.

**Log for iPhone5,1 on 9,3,3**
`clutch -b 23`
`2017-04-16 09:32:54.591 clutch[2136:320544] command: Only dump binary files from specified bundleID`
`Zipping Instagram.app`
`Error: Could not obtain mach port, either the process is dead (codesign error?) or entitlements were not properly signed!?`

`Error: Failed to dump <InstagramNotificationExtension> with arch armv7`

`2017-04-16 09:32:59.152 clutch[2136:320564] failed operation :(`
`2017-04-16 09:32:59.152 clutch[2136:320564] application <NSOperationQueue: 0x147711b0>{name = 'NSOperationQueue 0x147711b0'}`
`Error: Failed to dump <InstagramNotificationExtension>`

`2017-04-16 09:32:59.157 clutch[2136:320564] failed operation :(`
`2017-04-16 09:32:59.158 clutch[2136:320564] application <NSOperationQueue: 0x147711b0>{name = 'NSOperationQueue 0x147711b0'}`
`ASLR slide: 0x19000`
`Dumping <InstagramWatchKitExtension> (armv7)`
`Patched cryptid (32bit segment)`
`ASLR slide: 0x7d000`
`Dumping <InstagramShareExtension> (armv7)`
`Patched cryptid (32bit segment)`
`Writing new checksum`
`Writing new checksum`
`ASLR slide: 0x77000`
`Dumping <Instagram> (armv7)`
`Patched cryptid (32bit segment)`
`Writing new checksum`
`Zipping InstagramNotificationExtension.appex`
`Zipping InstagramShareExtension.appex`
`Zipping InstagramWatchKitExtension.appex`
`FAILED: <Instagram bundleID: com.burbn.instagram>`
`Finished dumping com.burbn.instagram in 50.3 seconds`

This only produces "InstagramNotificationExtension"

**Log for iPad4,4 on 9,3,3**
`clutch -b 21`
`2017-04-16 09:36:01.425 clutch[14806:475842] command: Only dump binary files from specified bundleID
Zipping Instagram.app`
`Error: Could not obtain mach port, either the process is dead (codesign error?) or entitlements were not properly signed!`

`Error: Failed to dump <InstagramNotificationExtension> with arch arm64`

`2017-04-16 09:36:03.803 clutch[14806:475861] failed operation :(`
`2017-04-16 09:36:03.804 clutch[14806:475861] application <NSOperationQueue: 0x14e7d64e0>{name = 'NSOperationQueue 0x14e7d64e0'}`
`Error: Failed to dump <InstagramNotificationExtension>`

`2017-04-16 09:36:03.804 clutch[14806:475861] failed operation :(`
`2017-04-16 09:36:03.804 clutch[14806:475861] application <NSOperationQueue: 0x14e7d64e0>{name = 'NSOperationQueue 0x14e7d64e0'}`
`Error: Could not obtain mach port, either the process is dead (codesign error?) or entitlements were not properly signed!`

`Error: Failed to dump <InstagramWatchKitExtension> with arch arm64`

`2017-04-16 09:36:04.036 clutch[14806:475863] failed operation :(`
`2017-04-16 09:36:04.036 clutch[14806:475863] application <NSOperationQueue: 0x14e7d4ac0>{name = 'NSOperationQueue 0x14e7d4ac0'}`
`Error: Failed to dump <InstagramWatchKitExtension>`

`2017-04-16 09:36:04.038 clutch[14806:475863] failed operation :(`
`2017-04-16 09:36:04.038 clutch[14806:475863] application <NSOperationQueue: 0x14e7d4ac0>{name = 'NSOperationQueue 0x14e7d4ac0'}`
`ASLR slide: 0x100004000`
`Dumping <InstagramShareExtension> (arm64)`
`Patched cryptid (64bit segment)`
`Writing new checksum`
`ASLR slide: 0x1000ec000`
`Dumping <Instagram> (arm64)`
`Patched cryptid (64bit segment)`
`Zipping InstagramNotificationExtension.appex`
`Zipping InstagramShareExtension.appex`
`Writing new checksum`
`Zipping InstagramWatchKitExtension.appex`
`FAILED: <Instagram bundleID: com.burbn.instagram>`
`Finished dumping com.burbn.instagram in 20.5 seconds`

This only produces "InstagramNotificationExtension" and "InstagramNotificationExtension"

**Comment by nothingzz** [comment] 2017-08-07 17:02
Did you solve this problem？

**Comment by asterix23** [comment] 2017-09-26 18:03
We are hitting this problem as well.  Any update?

**Comment by Tatsh** [comment] 2017-12-22 09:50
Duplicate of #127

**Closed by Tatsh** 2017-12-22 09:50 UTC
Labels: bug
