### ISSUE TITLE
Issues issuing Clutch2 -i

### ISSUE THREAD

**Issue by dolmx** [KJCracks/Clutch#96] opened 2015-06-21 09:29 UTC
iPhone:~ root# Clutch2 --clean
iPhone:~ root# 
iPhone:~ root# Clutch2 -i          
2015-06-21 12:28:12.875 Clutch2[739:5212] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x185f6659c 0x1966bc0e4 0x185e54798 0x185e545c8 0x10006a3b8 0x10006a7c4 0x100079a44 0x10007aabc 0x10005bc64 0x10005b178 0x10007a130 0x196d2aa08)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
iPhone:~ root#

**Comment by ttwj** [comment] 2015-06-21 09:52
Are you using the latest version? This bug should've been fixed in RC4.. Also, what iOS version are you on?

**Comment by dolmx** [comment] 2015-06-21 12:15
Hi,

on iOS 8.1.2, Clutch2 RC4.

iPhone:~ root# uname -a
Darwin iPhone 14.0.0 Darwin Kernel Version 14.0.0: Mon Nov  3 22:27:30 PST 2014; root:xnu-2783.3.22~1/RELEASE_ARM64_T7000 iPhone7,2 arm64 N61AP Darwin
iPhone:~ root# Clutch2 --version
Clutch2: version 2.0 RC4
iPhone:~ root# Clutch2 -i       
2015-06-21 15:14:11.807 Clutch2[658:4047] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x18650e59c 0x196c640e4 0x1863fc798 0x1863fc5c8 0x1000423b8 0x1000427c4 0x100051a44 0x100052abc 0x100033c64 0x100033178 0x100052130 0x1972d2a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
iPhone:~ root#

**Comment by kotik** [comment] 2015-06-30 13:25
Have the same issue with iOS 8.3 and Clutch2 RC4

**Comment by mohybanger** [comment] 2015-08-11 00:41
888:~ mobile$ su
Password:
888:/var/mobile root# clutch -C
Unknown command line option -C, try --help!
Usage: clutch [OPTIONS]
-b --binary-dump <value> Only dump binary files from specified bundleID
-d --dump <value>        Dump specified bundleID into .ipa file
-i --print-installed     Print installed applications
   --clean               Clean /var/tmp/clutch directory
   --version             Display version and exit
-? --help                Display this help and exit

888:/var/mobile root# YES
sh: YES: command not found
888:/var/mobile root# --help
sh: --help: command not found
888:/var/mobile root# clutch --help
Usage: clutch [OPTIONS]
-b --binary-dump <value> Only dump binary files from specified bundleID
-d --dump <value>        Dump specified bundleID into .ipa file
-i --print-installed     Print installed applications
   --clean               Clean /var/tmp/clutch directory
   --version             Display version and exit
-? --help                Display this help and exit

888:/var/mobile root# clutch --clean
888:/var/mobile root# clutch --print-installed
2015-08-11 04:57:16.465 clutch[27778:1291121] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x1844602d8 0x195c840e4 0x18434c9c8 0x18434c7f8 0x10002a3b8 0x10002a7c4 0x100039a44 0x10003aabc 0x10001bc64 0x10001b178 0x10003a130 0x196302a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
888:/var/mobile root#

iphone 6, version 8.3
clutch 2 rc4

**Comment by Tatsh** [comment] 2016-01-29 07:12
Built from source with latest code (had to fix a debug line), same crash:

```
copula:~ root# ./clutch -i
2016-01-28 23:11:05.967 clutch[1585:86054] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x18215cf5c 0x19764bf80 0x18204b8e8 0x18204b780 0x1000f1fa0 0x1000f23a0 0x1001117b4 0x100112968 0x100101694 0x100100bec 0x100111f48 0x197e6a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
copula:~ root# uname -a
Darwin copula 15.0.0 Darwin Kernel Version 15.0.0: Thu Aug 20 13:11:13 PDT 2015; root:xnu-3248.1.3~1/RELEASE_ARM64_S8000 iPhone8,2 arm64 N66mAP Darwin
```

**Comment by ttwj** [comment] 2016-01-29 07:20
this is very strange, I've been unable to replicate this bug.. Could you replace ApplicationsManager.m with the code below and post the output? thanks!

`//
//  ApplicationsManager.m
//  Clutch
//
//  Created by Anton Titkov on 09.02.15.
//
//

#define applistCachePath @"applist-cache.plist"
#define dumpedAppPath @"/etc/dumped.clutch"

#import <dlfcn.h>
#import "ApplicationsManager.h"
#import "FBApplicationInfo.h"
#import "LSApplicationProxy.h"
#import "LSApplicationWorkspace.h"

typedef NSDictionary* (*MobileInstallationLookup)(NSDictionary *options);

@interface ApplicationsManager ()
{
    void * _MIHandle;
    MobileInstallationLookup _mobileInstallationLookup;
    NSMutableArray* _cachedApps;
}
@end

@implementation ApplicationsManager

+ (instancetype)sharedInstance
{
    static dispatch_once_t pred;
    static id shared = nil;
    
    dispatch_once(&pred, ^{
        shared = [self new];
    });
    
    return shared;
}

- (instancetype)init
{
    self = [super init];
    if (self) {
        _MIHandle = dlopen("/System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation", RTLD_NOW);
        
        _mobileInstallationLookup = NULL;
        
        if (_MIHandle)
            _mobileInstallationLookup = dlsym(_MIHandle,"MobileInstallationLookup");
        
    }
    if ([[NSFileManager defaultManager] fileExistsAtPath:applistCachePath]) {
        _cachedApps = [[NSMutableArray alloc] initWithContentsOfFile:applistCachePath];
    }
    else {
        _cachedApps = [NSMutableArray new];
    }
    return self;
}

- (NSDictionary *)_allApplications
{
    _cachedApps = [NSMutableArray new];
    NSMutableDictionary *returnValue = [NSMutableDictionary new];
    
    NSDictionary* options = @{@"ApplicationType":@"User",
                              @"ReturnAttributes":@[@"CFBundleShortVersionString",
                                                    @"CFBundleVersion",
                                                    @"Path",
                                                    @"CFBundleDisplayName",
                                                    @"CFBundleExecutable",
                                                    @"MinimumOSVersion"]};
    
    if (_mobileInstallationLookup) {
        NSLog(@"using MSLookup");
        NSDictionary *installedApps;
        
        installedApps = _mobileInstallationLookup(options);
        
        
        for (NSString *bundleID in [installedApps allKeys])
        {
            NSDictionary *appI=installedApps[bundleID];
            
            NSURL *bundleURL = [NSURL fileURLWithPath:appI[@"Path"]];
           
            NSString *scinfo=[bundleURL.path stringByAppendingPathComponent:@"SC_Info"];
           
            BOOL isDirectory;
            
            BOOL purchased = [[NSFileManager defaultManager]fileExistsAtPath:scinfo isDirectory:&isDirectory];
            
            if (purchased && isDirectory) {
                NSString* name = appI[@"CFBundleDisplayName"];
                if (name == nil) {
                    name = appI[@"CFBundleExecutable"];
                }
                NSLog(@"initializing %@ %@ %@ %@", bundleURL.URLByDeletingLastPathComponent, bundleURL, proxy.bundleURL, name, bundleID);
                NSDictionary* bundleInfo = @{@"BundleContainer":bundleURL.URLByDeletingLastPathComponent,
                                             @"BundleURL":bundleURL,
                                             @"DisplayName": name,
                                             @"BundleIdentifier": bundleID};
                Application *app =[[Application alloc]initWithBundleInfo:bundleInfo];
                [self cacheBundle:bundleInfo];
                returnValue[bundleID] = app;
            }
        }
        
    }else
    {
        NSLog(@"using LSAppWorkSpace");
        LSApplicationWorkspace* applicationWorkspace = [LSApplicationWorkspace defaultWorkspace];
        
        NSArray *proxies = [applicationWorkspace allApplications];
        
        
        for (FBApplicationInfo * proxy in proxies) {
            
            NSString *appType = [proxy performSelector:@selector(applicationType)];
            
            if ([appType isEqualToString:@"User"] && proxy.bundleContainerURL && proxy.bundleURL) {
                
                NSString *scinfo=[proxy.bundleURL.path stringByAppendingPathComponent:@"SC_Info"];
                
                BOOL isDirectory;
                
                BOOL purchased = [[NSFileManager defaultManager]fileExistsAtPath:scinfo isDirectory:&isDirectory];
                
                if (purchased && isDirectory) {
                    NSLog(@"initializing %@ %@ %@ %@", proxy.bundleContainerURL, proxy.bundleURL, ((LSApplicationProxy*) proxy).itemName, proxy.bundleIdentifier);
                    NSDictionary* bundleInfo = @{@"BundleContainer":proxy.bundleContainerURL,
                                                 @"BundleURL":proxy.bundleURL,
                                                 @"DisplayName": ((LSApplicationProxy*) proxy).itemName,
                                                 @"BundleIdentifier": proxy.bundleIdentifier};
                    Application *app =[[Application alloc]initWithBundleInfo:bundleInfo];
                    returnValue[proxy.bundleIdentifier] = app;
                    [self cacheBundle:bundleInfo];
                    
                }
            }
        }
        
    }
    dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0);
    dispatch_async(queue, ^{
        [_cachedApps writeToFile:applistCachePath atomically:YES];
    });
    
    return [returnValue copy];
}

- (NSDictionary *)installedApps
{
    return [self _allApplications];
}

-(NSDictionary*)_allCachedApplications {
    if ([_cachedApps count] < 1) {
        return [self _allApplications];
    }
    NSMutableDictionary* returnValue = [NSMutableDictionary new];
    for (NSDictionary* bundleInfo in _cachedApps) {
        Application *app =[[Application alloc]initWithBundleInfo:bundleInfo];
        returnValue[bundleInfo[@"BundleIdentifier"]] = app;
    }
    return returnValue;
}

-(void)cacheBundle:(NSDictionary*) bundle {
    [_cachedApps addObject:bundle];
}


- (NSArray *)dumpedApps
{
    NSString *dumpedPath = @""; //[NSString stringWithFormat:@"%@/", [[Preferences sharedInstance] ipaDirectory]];
    NSArray *array=[[NSArray alloc]initWithArray:[[NSFileManager defaultManager] contentsOfDirectoryAtPath:dumpedPath error:nil]];
    
    NSMutableArray *paths=[NSMutableArray new];
    
    for (int i=0; i<array.count; i++)
    {
        if (![[array[i] pathExtension] caseInsensitiveCompare:@"ipa"])
        {
            [paths addObject:array[i]];
        }
    }
    
    return paths;
}

@end
`

**Comment by Tatsh** [comment] 2016-01-29 07:23
I think that pasted wrong. Can you link to a gist?

**Comment by ttwj** [comment] 2016-01-29 07:24
https://gist.github.com/ttwj/e407c957b24d00ea434b

**Comment by Tatsh** [comment] 2016-01-29 07:28
Got the same error and those `NSLog()`s didn't run. So it must be happening earlier in the code.

From syslog (same as app output):

```
Jan 28 23:27:30 copula clutch[1770]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
```

**Comment by ttwj** [comment] 2016-01-29 07:30
is there an applist-cache.plist in where the executable is?

**Comment by Tatsh** [comment] 2016-01-29 07:30
Nope.

**Comment by Tatsh** [comment] 2016-01-29 07:34
Something to do with buffered output? Maybe writing to a file unbuffered with C APIs would work to see how far the code gets?

**Comment by Tatsh** [comment] 2016-01-29 07:38
The crash happens in the for loop in `main.m` `listApps()`.

**Comment by Tatsh** [comment] 2016-01-29 07:44
It's in `_allApplications` method `-[NSDictionary dictionaryWithObjects:forKeys:count]` call in `ApplicationsManager`.

**Comment by ttwj** [comment] 2016-01-29 07:46
thanks, did you `make debug` when compiling? the logs should be appearing in `_allApplications`

**Comment by Tatsh** [comment] 2016-01-29 07:55
I did use `make debug` but that wasn't really it.

I caught the exception and just `continue`d out of the loop. I have not yet inspected the cause of the exception. It is an `NSInvalidArgumentException` as we already know, to creating an `NSDictionary`.

```diff
diff --git a/Clutch/ApplicationsManager.m b/Clutch/ApplicationsManager.m
index 82ca271..7dd1aae 100644
--- a/Clutch/ApplicationsManager.m
+++ b/Clutch/ApplicationsManager.m
@@ -112,6 +112,7 @@ typedef NSDictionary* (*MobileInstallationLookup)(NSDictionary *options);
         LSApplicationWorkspace* applicationWorkspace = [LSApplicationWorkspace defaultWorkspace];

         NSArray *proxies = [applicationWorkspace allApplications];
+        NSDictionary *bundleInfo = nil;


         for (FBApplicationInfo * proxy in proxies) {
@@ -127,10 +128,17 @@ typedef NSDictionary* (*MobileInstallationLookup)(NSDictionary *options);
                 BOOL purchased = [[NSFileManager defaultManager]fileExistsAtPath:scinfo isDirectory:&isDirectory];

                 if (purchased && isDirectory) {
-                    NSDictionary* bundleInfo = @{@"BundleContainer":proxy.bundleContainerURL,
+                    @try {
+                    bundleInfo = @{@"BundleContainer":proxy.bundleContainerURL,
                                                  @"BundleURL":proxy.bundleURL,
                                                  @"DisplayName": ((LSApplicationProxy*) proxy).itemName,
                                                  @"BundleIdentifier": proxy.bundleIdentifier};
+                    }
+                    @catch (NSException *exc) {
+                       printf("Exception!!!\n");
+                       bundleInfo = nil;
+                    }
+                    if (!bundleInfo) { continue; }
                     Application *app =[[Application alloc]initWithBundleInfo:bundleInfo];
                     returnValue[proxy.bundleIdentifier] = app;
                     [self cacheBundle:bundleInfo];
```

**Comment by ttwj** [comment] 2016-01-29 07:59
could you add ` NSLog(@"%@ %@ %@ %@", proxy.bundleContainerURL, proxy.bundleURL, ((LSApplicationProxy*) proxy).itemName, proxy.bundleIdentifier);` before it initialises the bundleInfo dictionary? it's probably a missing DisplayName

**Comment by Tatsh** [comment] 2016-01-29 08:00
Found the offending app.

```
DEBUG | ApplicationsManager.m:-[ApplicationsManager _allApplications] [Line 138] | exception: file:///private/var/mobile/Containers/Bundle/Application/3AB3C729-F20B-4FD5-94E9-106F4688F339, file:///private/var/mobile/Containers/Bundle/Application/3AB3C729-F20B-4FD5-94E9-106F4688F339/OpenVPN.app, (null), net.openvpn.connect.app```

OpenVPN Connect !!

But of course there can be others.

**Comment by Tatsh** [comment] 2016-01-29 08:07
So yeah, it is a NULL `itemName` for some apps.

Also, got a weird error. Maybe it's my device or iOS 9+ (maybe I just need to reboot), but it seems like Clutch randomly dies with exit code 9. If I launch an app, Clutch starts working again. Might be a keychain access thing.

**Comment by ttwj** [comment] 2016-01-29 08:11
You need to use `ldid` to codesign the binary on your device, there's some problem with the Makefile's codesign. Also could you add this before the `@try`

`NSLog(@"%@ %@", proxy.displayName, proxy.fallbackFolderName)`

Thanks

**Comment by Tatsh** [comment] 2016-01-29 08:15
Throws an exception.

```
2016-01-29 00:14:19.501 clutch[3115:106053] -[LSApplicationProxy displayName]: unrecognized selector sent to instance 0x15fe0bf80
2016-01-29 00:14:19.505 clutch[3115:106053] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[LSApplicationProxy displayName]: unrecognized selector sent to instance 0x15fe0bf80'
*** First throw call stack:
(0x18215cf5c 0x19764bf80 0x182163c6c 0x182160c14 0x182064dcc 0x100014f50 0x100015834 0x1000383f4 0x1000395a8 0x100027f10 0x100027468 0x100038b88 0x197e6a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
bash: line 1:  3115 Abort trap: 6           ./clutch -i
```

**Comment by ttwj** [comment] 2016-01-29 08:16
How about `proxy.itemID`?

**Comment by Tatsh** [comment] 2016-01-29 08:16
`fallbackFolderName` does not work either.

**Comment by Tatsh** [comment] 2016-01-29 08:18
`ApplicationsManager.m:131:20: error: property 'itemID' not found on object of type 'FBApplicationInfo *'`

**Comment by ttwj** [comment] 2016-01-29 08:19
change `for (FBApplicationInfo * proxy in proxies) {` to `for (LSApplicationProxy * proxy in proxies) {`

**Comment by Tatsh** [comment] 2016-01-29 08:21
Won't work because that type doesn't have the same properties:

```
ApplicationsManager.m:122:60: error: property 'bundleContainerURL' not found on object of type 'LSApplicationProxy *'
            if ([appType isEqualToString:@"User"] && proxy.bundleContainerURL && proxy.bundleURL) {
                                                           ^
ApplicationsManager.m:122:88: error: property 'bundleURL' not found on object of type 'LSApplicationProxy *'
            if ([appType isEqualToString:@"User"] && proxy.bundleContainerURL && proxy.bundleURL) {
```

I tried casting in the NSLog() line and it did not seem to get a usable value.

**Comment by ttwj** [comment] 2016-01-29 08:22
Sorry, this object is really strange, it's like a mix of FBApplicationInfo and LSApplicationProxy (??), could you try `(LSApplicationProxy*)proxy.itemID` and `(LSApplicationProxy*)proxy.localizedName`

**Comment by Tatsh** [comment] 2016-01-29 08:25
Every app on my phone gives an ID, except OpenVPN Connect.

```
DEBUG | ApplicationsManager.m:-[ApplicationsManager _allApplications] [Line 131] | 0, OpenVPN
```

It looks like `localizedName` could work when you get a NULL `itemName`.

**Comment by ttwj** [comment] 2016-01-29 08:26
thanks, I'll push an update for it!

**Comment by Tatsh** [comment] 2016-01-29 08:27
If you want to copy what I have:

```diff
diff --git a/Clutch/ApplicationsManager.m b/Clutch/ApplicationsManager.m
index 82ca271..9609bd3 100644
--- a/Clutch/ApplicationsManager.m
+++ b/Clutch/ApplicationsManager.m
@@ -112,6 +112,7 @@ typedef NSDictionary* (*MobileInstallationLookup)(NSDictionary *options);
         LSApplicationWorkspace* applicationWorkspace = [LSApplicationWorkspace defaultWorkspace];

         NSArray *proxies = [applicationWorkspace allApplications];
+        NSDictionary *bundleInfo = nil;


         for (FBApplicationInfo * proxy in proxies) {
@@ -127,9 +128,13 @@ typedef NSDictionary* (*MobileInstallationLookup)(NSDictionary *options);
                 BOOL purchased = [[NSFileManager defaultManager]fileExistsAtPath:scinfo isDirectory:&isDirectory];

                 if (purchased && isDirectory) {
-                    NSDictionary* bundleInfo = @{@"BundleContainer":proxy.bundleContainerURL,
+                    NSString *itemName = ((LSApplicationProxy*) proxy).itemName;
+                    if (!itemName) {
+                        itemName = ((LSApplicationProxy*)proxy).localizedName;
+                    }
+                    bundleInfo = @{@"BundleContainer":proxy.bundleContainerURL,
                                                  @"BundleURL":proxy.bundleURL,
-                                                 @"DisplayName": ((LSApplicationProxy*) proxy).itemName,
+                                                 @"DisplayName": itemName,
                                                  @"BundleIdentifier": proxy.bundleIdentifier};
                     Application *app =[[Application alloc]initWithBundleInfo:bundleInfo];
                     returnValue[proxy.bundleIdentifier] = app;
diff --git a/Clutch/Dumper.m b/Clutch/Dumper.m
index 6f58a43..f6778f1 100644
--- a/Clutch/Dumper.m
+++ b/Clutch/Dumper.m
@@ -84,7 +84,7 @@ exit_with_errno (int err, const char *prefix)
         //thinHeader.header.flags |= MH_PIE;
         //[self.originalFileHandle replaceBytesInRange:NSMakeRange(_thinHeader.offset, sizeof(_thinHeader.header)) withBytes:&_thinHeader.header];
     }else {
-        DumpeDebugLog(@"to MH_PIE or not to MH_PIE, that is the question");
+        DumperDebugLog(@"to MH_PIE or not to MH_PIE, that is the question");
     }

     pid_t pid = 0;
```

**Closed** 2016-01-30 01:22 UTC
